# Site settings
title: Boot-Start || Data Intelligence & IT experts
email: contact@boot-start.com
description: Boot-Start provides a team of talented developers and data scientists to help your project.
baseurl: ""
url: "http://www.boot-start.com"
twitter_username: boot_start
github_username:  boot-start
facebook_username: bootstart
# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  #- jekyll-less

defaults:
 -
   scope:
     path: "fr/service"
   values:
     language: fr
     category: service
     layout: page
 -
   scope:
     path: "en/service"
   values:
     language: en
     category: service
     layout: page
 -
   scope:
     path: "fr/offer"
   values:
     language: fr
     category: offer
     layout: page
 -
   scope:
     path: "en/offer"
   values:
     language: en
     category: offer
     layout: page
 -
   scope:
     path: "fr/products"
   values:
     language: fr
     category: product
     layout: page
 -
   scope:
     path: "en/products"
   values:
     language: en
     category: product
     layout: page
 -
   scope:
     path: "fr/expertise"
   values:
     language: fr
     category: expertise
     layout: page
 -
   scope:
     path: "fr/project"
   values:
     language: fr
     category: project
     layout: page
 -
   scope:
     path: "en/expertise"
   values:
     language: en
     category: expertise
     layout: page
 -
    scope:
      path: "en/team"
    values:
      language: en
      category: team
      layout: page
 -
    scope:
      path: "fr/team"
    values:
      language: fr
      category: team
      layout: page
 -
    scope:
      path: "en/portfolio"
    values:
      language: en
      category: portfolio
      layout: page
 -
    scope:
      path: "fr/portfolio"
    values:
      language: fr
      category: portfolio
      layout: page
 -
    scope:
      path: "en/jobs"
    values:
      language: en
      category: jobs
      layout: page
 -
    scope:
      path: "fr/jobs"
    values:
      language: fr
      category: jobs
      layout: page
 -
    scope:
      path: "en/swiper"
    values:
      language: en
      category: swiper
      sitemap: false
 -
    scope:
      path: "fr/swiper"
    values:
      language: fr
      category: swiper
      sitemap: false

t:
  en:
    lang:
      en: English
      fr: French
    more: more
    menu:
      home: Home
      products: Products
      expertise: Expertise
      project: Whole Project
      team: Team
      portfolio: Portfolio
      contact: Contact
      jobs: Jobs
    project:
      heading: "We help and develop your inovative project"
      subheading: "Notre métier est de vous construire la solution la plus adaptée et fonctionnelle"
      br:
        subheading: "we work with a 'sprint' method"
      advice:
        heading: "Advices and strategy"
        subheading: "We bring you a vision about all the possibilities and suggestions according to your strategy"
      poc:
        heading: " Proof Of Concept"
        subheading: "You can test fastly your project with a fonctional prototype"
      integration:
        heading: " Developement et Integration"
        subheading: "We create with you the product the as efficient as possible"
      expertise:
        heading: " Our super powers"
        subheading: "Above all, Boot-Start is a team with complementaries and advanced skills"
      products:
        heading: " Nos super products"
        subheading: "Here are products we developed and we can integrate in your project"
    product:
      heading: "Products"
      subheading: "We mutualize the software we develop, some made available as products."
    service:
      heading: "Services"
      subheading: "We have a wide scope of tasks we can help you get done."
    expertise:
      heading: "Expertise"
      subheading: "Here are some of the advanced topics we can work on for you."
    portfolio:
      heading: "Portfolio"
      subheading: "They trust us and we helped them get things done."
    team:
      heading: "Our Amazing Team"
      subheading: "Dedicated to make the best out of few."
      description: "We chose to build a team of members who, even when specialized, have a clear
                    understanding and sensitivity to the other aspects of the greater picture.
                    Thus all of are members will have a global vision of the projects they work on, should it be
                    technical, design, business, user experience, etc."
    contact:
       heading: "Contact Us"
       callus: "Drop us a line, we'll be happy to answer."
       callusat: "Call Us At"
       emailus: "or send us a message:"
       name: "Your Name"
       email: "Your Email"
       phone: "Your Phone"
       message: "Your Message"
       send: "Send"
    footer:
       terms: Terms Of Use
       copyright: Copyright &copy; Boot-Start 2017

  fr:
    lang:
      en: Anglais
      fr: Français
    more: plus
    menu:
      home: Accueil
      service: Services
      project: Accompagnement
      products: Produits
      expertise: Expertise
      team: Equipe
      portfolio: Portfolio
      contact: Contact
      jobs: Emploi
    offer:
      heading: "Nos Services"
      subheading: "2 types d'approches avec nos clients partenaires, l'accompagnement sur un projet global et l'expertise sur un sujet technique précis."
    service:
      heading: "Services"
      subheading: "Nous avons un large panel de tâches que nous pouvons vous aider à accomplir."
    project:
      heading: "Nous accompagnons et développons pour vous votre projet innovant "
      subheading: "Notre métier est de vous construire la solution la plus adaptée et fonctionnelle"
      advice:
        heading: "Conseil et stratégie"
        subheading: "Nous vous apportons une vision globale des solutions et des suggestions selon votre stratégie"
      poc:
        heading: " Proof Of Concept"
        subheading: "Nous vous proposons de tester rapidement votre concept avec un protoype fonctionnel"
      integration:
        heading: " Développement et Intégration"
        subheading: "Notre métier est de vous construire le produit le plus adapté et efficace"
      expertise:
        heading: " Nos super pouvoirs"
        subheading: "Boot-Start c'est avant tout des compétences pointues et complémentaires"
      products:
        heading: " Nos super produits"
        subheading: "Voici des produits déjà développés par Boot-Start et que nous pouvons intégrer chez vous"
    products:
      heading: "Produits"
      subheading: "Nous mutualisons nos développements, certains devenant des produits."
    expertise:
      heading: Expertise
      subheading: "Voici quelques sujets avancés sur lesquels nous pouvons vous accompagner."
      data:
        heading: Expertise Traitement de données
        subheading: "Voici quelques sujets avancés sur lesquels nous pouvons vous accompagner."
      ml:
        heading: Expertise Data Intelligence
        subheading: "Voici quelques technologies de pointe que nous avons l'habitude d'adapter aux innovations d'entreprise"

      dev:
                heading: Expertise projet agile
                subheading: " Nous avons l'habitude de travailler sur des projets complets "
    portfolio:
      heading: Portfolio
      subheading: "Ils nous font confiance et nous les avons aidés à concrétiser leurs idées."
    team:
      heading: "Notre Equipe Incroyable"
      subheading: "Une synergie de talents dévoués à votre projet."
      description: "Nous construisons une équipe de personnes, qui bien que spécialisées, ont une compréhension et une sensibilité aux autres aspects de la vue d'ensemble.
                    Ainsi toutes les personnes de notre équipe travaillant sur un projet en ont une vision globale, que ce soit sur les aspects techniques, design, business, expérience utilisateur, ou autres."
    contact:
       heading: "Contactez Nous"
       callus: "Passez nous un coup de fil, nous serons ravis de répondre :"
       callusat: "Appelez-nous au"
       emailus: "ou envoyez nous un email :"
       name: "Votre nom"
       email: "Votre email"
       phone: "Votre numéro de téléphone"
       message: "Votre message"
       send: Envoyer
    footer:
       terms: "Mentions Légales"
       copyright: Copyright &copy; Boot-Start 2017
