# Site settings
title: Boot-Start || Bootstrap your Startup
email: contact@boot-start.com
description: "Boot-Start provides a team of talented developers to help you bootstrap your startup project."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: boot_start
github_username:  boot-start
facebook_username: bootstart
# Build settings
markdown: kramdown
permalink: pretty

# gems: ['jekyll-less']
