# Site settings
title: Boot-Start || Bootstrap your Startup
email: contact@boot-start.com
description: Boot-Start provides a team of talented developers to help you bootstrap your startup project.
baseurl: ""
url: "http://www.boot-start.com"
twitter_username: boot_start
github_username:  boot-start
facebook_username: bootstart
# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
  #- jekyll-sitemap
  #- jekyll-less

defaults:
 -
   scope:
     path: "service/fr"
   values:
     language: fr
     category: service
     layout: page
 -
   scope:
     path: "service/en"
   values:
     language: en
     category: service
     layout: page
 -
    scope:
      path: "team/en"
    values:
      language: en
      category: team
      layout: page
 -
    scope:
      path: "team/fr"
    values:
      language: fr
      category: team
      layout: page
 -
    scope:
      path: "swiper/en"
    values:
      language: en
      category: swiper
      sitemap: false
 -
    scope:
      path: "swiper/fr"
    values:
      language: fr
      category: swiper
      sitemap: false

t:
  en:
    lang:
      en: English
      fr: French
    menu:
      service: Services
      expertise: Expertise
      team: Team
      portfolio: Portfolio
      contact: Contact
    service:
      heading: "Services"
      description: "We have a wide scope of tasks we can help you get done."
  fr:
    lang:
      en: Anglais
      fr: Français
    menu:
      service: Services
      expertise: Expertise
      team: Equipe
      portfolio: Portfolio
      contact: Contact
    service:
      heading: "Services"
      description: "Nous avons un large panel de tâche que nous pouvons vous aider à accomplir"
