# Site settings
title: Boot-Start || Bootstrap your Startup
email: contact@boot-start.com
description: Boot-Start provides a team of talented developers to help you bootstrap your startup project.
baseurl: ""
url: "http://www.boot-start.com"
twitter_username: boot_start
github_username:  boot-start
facebook_username: bootstart
# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  #- jekyll-less

defaults:
 -
   scope:
     path: "service/fr"
   values:
     language: fr
     category: service
     layout: page
 -
   scope:
     path: "service/en"
   values:
     language: en
     category: service
     layout: page
 -
   scope:
     path: "expertise/fr"
   values:
     language: fr
     category: expertise
     layout: page
 -
   scope:
     path: "expertise/en"
   values:
     language: en
     category: expertise
     layout: page
 -
    scope:
      path: "team/en"
    values:
      language: en
      category: team
      layout: page
 -
    scope:
      path: "team/fr"
    values:
      language: fr
      category: team
      layout: page
 -
    scope:
      path: "portfolio/en"
    values:
      language: en
      category: portfolio
      layout: page
 -
    scope:
      path: "portfolio/fr"
    values:
      language: fr
      category: portfolio
      layout: page
 -
    scope:
      path: "swiper/en"
    values:
      language: en
      category: swiper
      sitemap: false
 -
    scope:
      path: "swiper/fr"
    values:
      language: fr
      category: swiper
      sitemap: false

t:
  en:
    lang:
      en: English
      fr: French
    menu:
      service: Services
      expertise: Expertise
      team: Team
      portfolio: Portfolio
      contact: Contact
    service:
      heading: "Services"
      subheading: "We have a wide scope of tasks we can help you get done."
    expertise:
      heading: "Expertise"
      subheading: "Here are some of the advanced topics we can work on for you."
    portfolio:
      heading: "Portfolio"
      subheading: They trust us and we helped them get things done.
    team:
      heading: "Our Amazing Team"
      subheading: "Dedicated to make the best out of few."
      description: "We chose to build a team of members who, even when specialized, have a clear
                    understanding and sensitivity to the other aspects of the greater picture.
                    Thus all of are members will have a global vision of the projects they work on, should it be
                    technical, design, business, user experience, etc."
    contact:
       heading: "Contact Us"
       callus: "Drop us a line, we'll be happy to answer."
       callusat: "Call Us At"
       emailus: "or send us a message:"
       name: "Your Name"
       email: "Your Email"
       phone: "Your Phone"
       message: "Your Message"
       send: "Send"
    footer:
       terms: Terms Of Use

  fr:
    lang:
      en: Anglais
      fr: Français
    menu:
      service: Services
      expertise: Expertise
      team: Equipe
      portfolio: Portfolio
      contact: Contact
    service:
      heading: "Services"
      subheading: "Nous avons un large panel de tâches que nous pouvons vous aider à accomplir."
    expertise:
      heading: Expertise
      subheading: "Voici quelques sujets avancés sur lesquels nous pouvons vous accompagner."
    portfolio:
      heading: Portfolio
      subheading: "Ils nous font confiance et nous les avons aidés à concrétiser leurs idées."
    team:
      heading: "Notre Equipe Incroyable"
      subheading: "Dévouée à faire le maximum avec peu."
      description: "Nous construisons une équipe de personnes, bien que spécialisées, ont une compréhension et une sensibilité aux autres aspects de la vue d'ensemble.
                    Ainsi toutes les personnes de notre équipe travaillant sur un projet en ont une vision global, que ce soit sur les aspects techniques, design, business, expérience utilisateur, etc."
    contact:
       heading: "Contactez Nous"
       callus: "Passez nous un coup de fil, on sera ravis de répondre:"
       callusat: "Appelez-nous au"
       emailus: "ou envoyez nous un email:"
       name: "Votre nom"
       email: "Votre email"
       phone: "Votre numéro de téléphone"
       message: "Votre message"
       send: Envoyer
    footer:
       terms: "Mentions Légales"
